[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
intake = { path = "../intake" }
clearinghouse = { path = "../clearinghouse" }
insurance = { path = "../insurance" }
chrono = "0.4.41"
serde_json = "1.0.142"
